language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
before_install:
  - sudo apt-get install -y python3-pip libglib2.0-dev

script:
  - python3 setup.py install
  - python3 -c "import avea;print(avea)"
